In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
print (os.getcwd())

C:\Users\CSELAB-6


In [4]:
os.chdir ('C:\\Users\\CSELAB-6\\Downloads\\')

In [5]:
df=pd.read_csv("audi.csv")
display(df)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [6]:
import pandas_profiling as pf
display(pf.ProfileReport(df))

ImportError: cannot import name 'DataError' from 'pandas.core.base' (C:\Users\CSELAB-6\anaconda3\Lib\site-packages\pandas\core\base.py)

In [7]:
print (len(df))

10668


In [8]:
display (df.shape)

(10668, 9)

In [9]:
display (df.dtypes )

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [10]:
display (df.isna().sum() )

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [11]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [12]:
display (df.describe ())

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [13]:
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
display (X.shape)
display (X)

(10668, 8)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [14]:
Y = df.iloc[:,[2]].values
display (Y.shape)
display (Y)

(10668, 1)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [15]:
display(pd.DataFrame(X).head(5))

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

In [16]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])
display (X)

array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [18]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)
display (X.shape)
display (pd.DataFrame(X))

(10668, 11)

0    1    2    3  4     5      6  7    8     9    10
0      1.0  0.0  0.0  1.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  1.0  0.0  5  2016  36203  0   20  64.2  2.0
2      1.0  0.0  0.0  1.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  1.0  0.0  3  2017  25952  0  145  67.3  2.0
4      1.0  0.0  0.0  1.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  1.0  0.0  0.0  1.0  2  2020   4018  2  145  49.6  1.0
10664  1.0  0.0  0.0  1.0  2  2020   1978  2  150  49.6  1.0
10665  1.0  0.0  0.0  1.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  1.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  1.0  0.0  0.0  1.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 11 columns]

In [19]:
display (pd.DataFrame(X))

0    1    2    3  4     5      6  7    8     9    10
0      1.0  0.0  0.0  1.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  1.0  0.0  5  2016  36203  0   20  64.2  2.0
2      1.0  0.0  0.0  1.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  1.0  0.0  3  2017  25952  0  145  67.3  2.0
4      1.0  0.0  0.0  1.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  1.0  0.0  0.0  1.0  2  2020   4018  2  145  49.6  1.0
10664  1.0  0.0  0.0  1.0  2  2020   1978  2  150  49.6  1.0
10665  1.0  0.0  0.0  1.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  1.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  1.0  0.0  0.0  1.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 11 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
display (pd.DataFrame(X))

0         1         2         3         4         5         6   \
0      0.712333 -0.712333 -0.583268  1.200728 -1.123544 -0.046450 -0.386836   
1      0.712333 -0.712333  1.714479 -0.832828 -0.160831 -0.507834  0.483989   
2      0.712333 -0.712333 -0.583268  1.200728 -1.123544 -0.507834  0.217781   
3      0.712333 -0.712333  1.714479 -0.832828 -0.545916 -0.046450  0.047853   
4      0.712333 -0.712333 -0.583268  1.200728 -0.738459  0.876318 -0.971285   
...         ...       ...       ...       ...       ...       ...       ...   
10663  0.712333 -0.712333 -0.583268  1.200728 -0.738459  1.337702 -0.885343   
10664  0.712333 -0.712333 -0.583268  1.200728 -0.738459  1.337702 -0.972136   
10665  0.712333 -0.712333 -0.583268  1.200728 -0.738459  1.337702 -1.030381   
10666  0.712333 -0.712333  1.714479 -0.832828  0.609339 -0.046450 -0.688442   
10667  0.712333 -0.712333 -0.583268  1.200728  0.609339 -0.507834 -0.551913   

             7         8         9         10  
0      1.050783  0.357147  0.357550 -0.880218  
1     -0.954181 -1.578323  1.037130  0.114925  
2      1.050783 -1.429440  0.357550 -0.880218  
3     -0.954181  0.282706  1.276528  0.114925  
4      1.050783  0.282706 -0.090355 -1.543647  
...         ...       ...       ...       ...  
10663  1.050783  0.282706 -0.090355 -1.543647  
10664  1.050783  0.357147 -0.090355 -1.543647  
10665  1.050783  0.357147 -0.090355 -1.543647  
10666  1.050783  0.357147 -0.221637 -0.880218  
10667  1.050783  0.357147 -0.221637 -0.880218  

[10668 rows x 11 columns]

In [22]:
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)
print (X.shape, Y.shape)
print (X_train.shape, Y_train.shape)
print (X_test.shape, Y_test.shape)

(10668, 11) (10668, 1)
(8534, 11) (8534, 1)
(2134, 11) (2134, 1)


In [24]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(X_train,Y_train)
display (regression)

RandomForestRegressor(random_state=0)

In [25]:
y_pred = regression.predict(X_test)
display (y_pred)

array([14274.37, 23493.8 , 27351.24, ..., 46322.12, 31282.2 ,  9942.21])

In [26]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[14274.37 14998.  ]
 [23493.8  21950.  ]
 [27351.24 28990.  ]
 ...
 [46322.12 45995.  ]
 [31282.2  30500.  ]
 [ 9942.21  8400.  ]]


In [27]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))

R2 Score  0.952853902119688
Mean Absolute Error 1543.1525118511943


In [28]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)
print(reg)

LinearRegression()


In [29]:
y_pred = reg.predict(X_test)
display (y_pred)

array([[13070.16465137],
       [29355.41465137],
       [31909.91465137],
       ...,
       [42624.41465137],
       [31530.91465137],
       [ 7305.16465137]])

In [30]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[13070.16465137 14998.        ]
 [29355.41465137 21950.        ]
 [31909.91465137 28990.        ]
 ...
 [42624.41465137 45995.        ]
 [31530.91465137 30500.        ]
 [ 7305.16465137  8400.        ]]


In [31]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))

R2 Score  0.7916359646001984
Mean Absolute Error 3381.2061900544168


In [32]:
y_pred = reg.predict(X)
display (y_pred)



array([[14636.66465137],
       [20640.66465137],
       [13819.16465137],
       ...,
       [19412.41465137],
       [21001.66465137],
       [16697.41465137]])

In [33]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14636.664651  
1             2.0  20640.664651  
2             1.4  13819.164651  
3             2.0  19917.164651  
4             1.0  17355.914651  
...           ...           ...  
10663         1.0  19195.664651  
10664         1.0  19282.414651  
10665         1.0  19412.414651  
10666         1.4  21001.664651  
10667         1.4  16697.414651  

[10668 rows x 10 columns]

In [34]:
from sklearn.ensemble import  ExtraTreesRegressor
ET_Model=ExtraTreesRegressor(n_estimators = 120)
ET_Model.fit(X_train,Y_train)
y_predict=ET_Model.predict(X_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_predict))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_predict))


R2 Score  0.9567037911652442
Mean Absolute Error 1541.2926970738313


In [35]:
y_pred = reg.predict(X)
display (y_pred)
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


array([[14636.66465137],
       [20640.66465137],
       [13819.16465137],
       ...,
       [19412.41465137],
       [21001.66465137],
       [16697.41465137]])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14636.664651  
1             2.0  20640.664651  
2             1.4  13819.164651  
3             2.0  19917.164651  
4             1.0  17355.914651  
...           ...           ...  
10663         1.0  19195.664651  
10664         1.0  19282.414651  
10665         1.0  19412.414651  
10666         1.4  21001.664651  
10667         1.4  16697.414651  

[10668 rows x 10 columns]

In [36]:

from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

# create random grid

rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = 1)


In [37]:
display (rCV.fit(X_train,Y_train))

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=3, n_jobs=1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

In [38]:
rf_pred=rCV.predict(X_test)
display (rf_pred)


array([14093.45066045, 23777.91214919, 28543.41523018, ...,
       48248.16121785, 31314.44485468, 10047.20883348])

In [39]:

from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(Y_test,rf_pred))
print('MSE',mean_squared_error(Y_test,rf_pred))



MAE 1522.6476604196646
MSE 5884065.577267097


In [40]:
display (r2_score(Y_test,rf_pred))

0.9571806408690929

In [41]:
from catboost import CatBoostRegressor
cat=CatBoostRegressor()
print (cat.fit(X_train,Y_train))


Learning rate set to 0.057452
0:	learn: 11211.8543675	total: 160ms	remaining: 2m 39s
1:	learn: 10723.2788577	total: 171ms	remaining: 1m 25s
2:	learn: 10248.0619284	total: 176ms	remaining: 58.5s
3:	learn: 9805.5827648	total: 181ms	remaining: 45.1s
4:	learn: 9397.5119353	total: 186ms	remaining: 36.9s
5:	learn: 9020.7339118	total: 189ms	remaining: 31.3s
6:	learn: 8666.0997213	total: 193ms	remaining: 27.4s
7:	learn: 8321.6548633	total: 197ms	remaining: 24.4s
8:	learn: 8003.8508898	total: 199ms	remaining: 21.9s
9:	learn: 7691.0165724	total: 202ms	remaining: 20s
10:	learn: 7409.8677470	total: 204ms	remaining: 18.3s
11:	learn: 7126.2962156	total: 206ms	remaining: 17s
12:	learn: 6874.1929774	total: 208ms	remaining: 15.8s
13:	learn: 6634.6963235	total: 211ms	remaining: 14.8s
14:	learn: 6392.8523276	total: 213ms	remaining: 14s
15:	learn: 6182.8109944	total: 215ms	remaining: 13.2s
16:	learn: 5997.3506305	total: 217ms	remaining: 12.6s
17:	learn: 5813.4187871	total: 219ms	remaining: 12s
18:	learn: 

160:	learn: 2450.2793215	total: 547ms	remaining: 2.85s
161:	learn: 2448.0917309	total: 551ms	remaining: 2.85s
162:	learn: 2446.3581340	total: 554ms	remaining: 2.84s
163:	learn: 2443.6454696	total: 557ms	remaining: 2.84s
164:	learn: 2441.1999030	total: 560ms	remaining: 2.83s
165:	learn: 2439.0718607	total: 563ms	remaining: 2.83s
166:	learn: 2436.0109805	total: 566ms	remaining: 2.82s
167:	learn: 2432.7880463	total: 570ms	remaining: 2.82s
168:	learn: 2431.3489440	total: 573ms	remaining: 2.82s
169:	learn: 2429.8932489	total: 575ms	remaining: 2.81s
170:	learn: 2425.3497179	total: 578ms	remaining: 2.8s
171:	learn: 2421.0051847	total: 582ms	remaining: 2.8s
172:	learn: 2419.6077823	total: 585ms	remaining: 2.79s
173:	learn: 2416.6549641	total: 587ms	remaining: 2.79s
174:	learn: 2412.7073147	total: 589ms	remaining: 2.78s
175:	learn: 2408.6008164	total: 592ms	remaining: 2.77s
176:	learn: 2407.2489633	total: 595ms	remaining: 2.77s
177:	learn: 2405.8193320	total: 597ms	remaining: 2.76s
178:	learn: 

393:	learn: 2078.3060368	total: 1.14s	remaining: 1.75s
394:	learn: 2077.3264619	total: 1.14s	remaining: 1.75s
395:	learn: 2075.7789552	total: 1.15s	remaining: 1.75s
396:	learn: 2074.9311463	total: 1.15s	remaining: 1.75s
397:	learn: 2073.6905549	total: 1.15s	remaining: 1.74s
398:	learn: 2072.7313603	total: 1.15s	remaining: 1.74s
399:	learn: 2072.4121170	total: 1.16s	remaining: 1.74s
400:	learn: 2072.0874713	total: 1.16s	remaining: 1.73s
401:	learn: 2071.1038332	total: 1.16s	remaining: 1.73s
402:	learn: 2070.6511633	total: 1.17s	remaining: 1.73s
403:	learn: 2069.8969900	total: 1.17s	remaining: 1.72s
404:	learn: 2068.8052387	total: 1.17s	remaining: 1.72s
405:	learn: 2068.3420506	total: 1.17s	remaining: 1.72s
406:	learn: 2067.8030349	total: 1.17s	remaining: 1.71s
407:	learn: 2066.5541098	total: 1.18s	remaining: 1.71s
408:	learn: 2065.8286643	total: 1.18s	remaining: 1.7s
409:	learn: 2064.9704713	total: 1.18s	remaining: 1.7s
410:	learn: 2064.5093535	total: 1.18s	remaining: 1.7s
411:	learn: 2

545:	learn: 1965.3187655	total: 1.52s	remaining: 1.26s
546:	learn: 1964.3215670	total: 1.52s	remaining: 1.26s
547:	learn: 1963.3209482	total: 1.52s	remaining: 1.26s
548:	learn: 1962.7543368	total: 1.53s	remaining: 1.25s
549:	learn: 1962.5504506	total: 1.53s	remaining: 1.25s
550:	learn: 1961.7210709	total: 1.53s	remaining: 1.25s
551:	learn: 1961.3065760	total: 1.54s	remaining: 1.25s
552:	learn: 1960.6309222	total: 1.54s	remaining: 1.24s
553:	learn: 1959.8471950	total: 1.54s	remaining: 1.24s
554:	learn: 1958.7715275	total: 1.54s	remaining: 1.24s
555:	learn: 1958.0946716	total: 1.55s	remaining: 1.24s
556:	learn: 1957.5217749	total: 1.55s	remaining: 1.23s
557:	learn: 1956.9520191	total: 1.55s	remaining: 1.23s
558:	learn: 1955.7420331	total: 1.55s	remaining: 1.23s
559:	learn: 1955.0826927	total: 1.55s	remaining: 1.22s
560:	learn: 1954.4699415	total: 1.56s	remaining: 1.22s
561:	learn: 1953.9101174	total: 1.56s	remaining: 1.22s
562:	learn: 1953.0667250	total: 1.56s	remaining: 1.21s
563:	learn

700:	learn: 1880.1133925	total: 1.9s	remaining: 810ms
701:	learn: 1879.3517164	total: 1.9s	remaining: 808ms
702:	learn: 1879.1662292	total: 1.91s	remaining: 805ms
703:	learn: 1878.8652956	total: 1.91s	remaining: 802ms
704:	learn: 1878.6830672	total: 1.91s	remaining: 800ms
705:	learn: 1878.0746914	total: 1.91s	remaining: 797ms
706:	learn: 1877.7960370	total: 1.92s	remaining: 794ms
707:	learn: 1877.4852938	total: 1.92s	remaining: 792ms
708:	learn: 1877.1837195	total: 1.92s	remaining: 789ms
709:	learn: 1876.5042816	total: 1.92s	remaining: 786ms
710:	learn: 1876.2226800	total: 1.93s	remaining: 783ms
711:	learn: 1875.3876633	total: 1.93s	remaining: 780ms
712:	learn: 1874.5786911	total: 1.93s	remaining: 777ms
713:	learn: 1874.4983003	total: 1.93s	remaining: 775ms
714:	learn: 1873.5738534	total: 1.94s	remaining: 772ms
715:	learn: 1872.9433404	total: 1.94s	remaining: 769ms
716:	learn: 1872.5007143	total: 1.94s	remaining: 766ms
717:	learn: 1872.2401761	total: 1.94s	remaining: 763ms
718:	learn: 

865:	learn: 1813.4415789	total: 2.29s	remaining: 354ms
866:	learn: 1813.1546716	total: 2.29s	remaining: 351ms
867:	learn: 1812.9116032	total: 2.29s	remaining: 349ms
868:	learn: 1812.3234936	total: 2.3s	remaining: 346ms
869:	learn: 1811.7069398	total: 2.3s	remaining: 344ms
870:	learn: 1811.0770368	total: 2.3s	remaining: 341ms
871:	learn: 1810.9323246	total: 2.31s	remaining: 338ms
872:	learn: 1810.8061829	total: 2.31s	remaining: 336ms
873:	learn: 1810.3884957	total: 2.31s	remaining: 333ms
874:	learn: 1810.1588847	total: 2.31s	remaining: 330ms
875:	learn: 1809.3764664	total: 2.31s	remaining: 328ms
876:	learn: 1808.8964567	total: 2.32s	remaining: 325ms
877:	learn: 1808.3185612	total: 2.32s	remaining: 322ms
878:	learn: 1807.9842819	total: 2.32s	remaining: 320ms
879:	learn: 1807.4019538	total: 2.32s	remaining: 317ms
880:	learn: 1806.9691984	total: 2.33s	remaining: 314ms
881:	learn: 1806.6574876	total: 2.33s	remaining: 312ms
882:	learn: 1806.2306810	total: 2.33s	remaining: 309ms
883:	learn: 1

In [42]:
cat_pred=cat.predict(X_test)
display (cat_pred)


array([13586.94928279, 23993.01765791, 28163.43857666, ...,
       46833.61295003, 31739.15820119,  9492.21201432])

In [43]:
display (r2_score(Y_test,cat_pred))

0.9645151911398052

In [44]:
import pickle 
# Saving model to disk
pickle.dump(cat, open('model.pkl','wb'))


In [45]:
model=pickle.load(open('model.pkl','rb'))
print (model.predict (X_train))


[14263.64338388 29423.70889624 11995.54473724 ... 21224.93594946
 17289.71027977 44935.91272296]
